// src/integrations/supabase/client.ts
// หรือไฟล์ที่คุณประกาศ supabase client ไว้

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const rawUrl = import.meta.env.VITE_SUPABASE_URL;
const rawKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY; // หรือ VITE_SUPABASE_ANON_KEY ถ้าคุณใช้ชื่อนี้

const SUPABASE_URL = (rawUrl ?? '').toString().trim();
const SUPABASE_PUBLISHABLE_KEY = (rawKey ?? '').toString().trim();

// ป้องกัน error แบบชี้ชัดก่อนส่งให้ supabase-js
if (!/^https?:\/\/[^"\s]+$/i.test(SUPABASE_URL)) {
  throw new Error(
    `[Supabase] Invalid VITE_SUPABASE_URL: "${rawUrl}" ` +
    `→ ตรวจ .env ให้เป็นรูปแบบ https://xxx.supabase.co (ห้ามมีช่องว่าง/อัญประกาศ)`
  );
}
if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('[Supabase] Missing VITE_SUPABASE_PUBLISHABLE_KEY (anon key)');
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
